/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fEgw1O62HBW
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/app/_components/ui/card"
import { Label } from "@/app/_components/ui/label"
import { Input } from "@/app/_components/ui/input"
import Link from "next/link"
import { Button } from "@/app/_components/ui/button"
import CustomButton from "../Button/Button"

export function Login() {
  return (
    (<div
      className="w-full h-screen bg-cover bg-center"
      style={{
        backgroundImage: "url('/placeholder.svg')",
      }}>
      <div className="flex items-center justify-center h-full">
        <Card className="mx-auto max-w-sm">
          <CardHeader className="space-y-1">
            <CardTitle className="text-2xl font-bold">Login</CardTitle>
            <CardDescription>Login or Register to Start Capturing Memories!!!</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="m@example.com" required type="email" />
              </div>
              <div className="relative space-y-2">
                <div className="flex items-center">
                  <Label htmlFor="password">Password</Label>
                  {/* <Link className="ml-auto inline-block text-sm underline" href="#">
                    Forgot your password?
                  </Link> */}
                </div>
                <Input id="password" required type="password" />
                <Button className="absolute bottom-1 right-1 h-7 w-7" size="icon" variant="ghost">
                  {/* <EyeIcon className="h-4 w-4" /> */}
                  <span className="sr-only">Toggle password visibility</span>
                </Button>
              </div>
              <Button className="w-full" type="submit">
                Login
              </Button>
              <CustomButton />
            </div>
            <div className="mt-4 text-center text-sm">
              Don't have an account?
              <Link className="underline" href="/signup">
                Sign up
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>)
  );
}


function EyeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 12s3-7 10-7 10 7 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}
