const OAUTH_DOMAIN = 'MBVSoTCM6bG83jQLQGf1DPMLnNGgeLEJ'
const OAUTH_Client_ID = 'MBVSoTCM6bG83jQLQGf1DPMLnNGgeLEJ'
const OAUTH_Client_Secret = 'jFIrJa11fNBDacMU59T4D2T2f46x8XV3hJ9IgPLVP_owWIkE2MuwVp5QtigWiAOI'


// Kintone URL

