import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@auth0/nextjs-auth0/client';

const inter = Inter({ subsets: ["latin"] });
import { getSession } from "@auth0/nextjs-auth0";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const { user } = await getSession() || {};

  return (
    <html lang="en">
      <UserProvider>
        <body className="flex h-full">
          {user ? (
            <>
              <div className="flex items-center justify-center gap-3">
                <div>
                  <p>Logged in as </p>
                  <p>{user.name}</p>
                </div>
                <img class="w-10 h-10 rounded-full" src={user.picture} alt="Rounded avatar" />
                <a href="/api/auth/logout" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Logout</a>
              </div>
            </>
          ) :
            (
              
                <div className="flex justify-center items-center">
                  <a href="/api/auth/login" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Login</a>
                </div>
            )}
          <div
            className="w-full h-screen bg-cover bg-center p-20"
          >
            {children}
          </div>
        </body>
      </UserProvider>
    </html>
  );
}
